import React from 'react';
import { FaWindows, FaPlaystation, FaXbox, FaLinux } from 'react-icons/fa';
import { BsNintendoSwitch } from 'react-icons/bs';
import { SiNintendogamecube, SiWiiu, SiWii, SiNintendo3Ds } from "react-icons/si";
import { GiConsoleController } from 'react-icons/gi';
import { PiVirtualReality } from "react-icons/pi";
import { FaApple } from "react-icons/fa";
import { IoLogoAndroid } from "react-icons/io";

const platformMapping: Record<number, { name: string; icon: React.ReactNode }> = {
  3: { name: "Linux", icon: <FaLinux /> },
  4: { name: "Nintendo 64", icon: <GiConsoleController /> },
  5: { name: "Wii", icon: <SiWii /> },
  6: { name: "PC (Microsoft Windows)", icon: <FaWindows /> },
  7: { name: "PlayStation", icon: <FaPlaystation /> },
  8: { name: "PlayStation 2", icon: <FaPlaystation /> },
  9: { name: "PlayStation 3", icon: <FaPlaystation /> },
  11: { name: "Xbox", icon: <FaXbox /> },
  12: { name: "Xbox 360", icon: <FaXbox /> },
  13: { name: "PC DOS", icon: <GiConsoleController /> },
  14: { name: "Mac", icon: <FaApple /> },
  15: { name: "Commodore C64/128", icon: <GiConsoleController /> },
  16: { name: "Amiga", icon: <GiConsoleController /> },
  18: { name: "Nintendo Entertainment System (NES)", icon: <BsNintendoSwitch /> },
  19: { name: "Super Nintendo Entertainment System (SNES)", icon: <BsNintendoSwitch /> },
  20: { name: "Nintendo DS", icon: <SiNintendo3Ds /> },
  21: { name: "Nintendo GameCube", icon: <SiNintendogamecube /> },
  22: { name: "Game Boy Color", icon: <BsNintendoSwitch /> },
  23: { name: "Dreamcast", icon: <GiConsoleController /> },
  24: { name: "Game Boy Advance", icon: <BsNintendoSwitch /> },
  25: { name: "Amstrad CPC", icon: <GiConsoleController /> },
  26: { name: "ZX Spectrum", icon: <GiConsoleController /> },
  27: { name: "MSX", icon: <GiConsoleController /> },
  29: { name: "Sega Mega Drive/Genesis", icon: <GiConsoleController /> },
  30: { name: "Sega 32X", icon: <GiConsoleController /> },
  32: { name: "Sega Saturn", icon: <GiConsoleController /> },
  33: { name: "Game Boy", icon: <BsNintendoSwitch /> },
  34: { name: "Android", icon: <IoLogoAndroid /> },
  35: { name: "Sega Game Gear", icon: <GiConsoleController /> },
  36: { name: "Xbox Live Arcade", icon: <FaXbox /> },
  37: { name: "Nintendo 3DS", icon: <SiNintendo3Ds /> },
  38: { name: "PlayStation Portable", icon: <FaPlaystation /> },
  39: { name: "iOS", icon: <FaApple /> },
  41: { name: "Wii U", icon: <SiWiiu /> },
  42: { name: "N-Gage", icon: <GiConsoleController /> },
  44: { name: "Tapwave Zodiac", icon: <GiConsoleController /> },
  45: { name: "PlayStation Network", icon: <FaPlaystation /> },
  46: { name: "PlayStation Vita", icon: <FaPlaystation /> },
  47: { name: "Virtual Console (Nintendo)", icon: <BsNintendoSwitch /> },
  48: { name: "PlayStation 4", icon: <FaPlaystation /> },
  49: { name: "Xbox One", icon: <FaXbox /> },
  50: { name: "3DO Interactive Multiplayer", icon: <GiConsoleController /> },
  51: { name: "Family Computer Disk System", icon: <GiConsoleController /> },
  52: { name: "Arcade", icon: <GiConsoleController /> },
  53: { name: "MSX2", icon: <GiConsoleController /> },
  55: { name: "Mobile", icon: <GiConsoleController /> },
  56: { name: "WiiWare", icon: <GiConsoleController /> },
  57: { name: "WonderSwan", icon: <GiConsoleController /> },
  58: { name: "Super Famicom", icon: <BsNintendoSwitch /> },
  59: { name: "Atari 2600", icon: <GiConsoleController /> },
  60: { name: "Atari 7800", icon: <GiConsoleController /> },
  61: { name: "Atari Lynx", icon: <GiConsoleController /> },
  62: { name: "Atari Jaguar", icon: <GiConsoleController /> },
  63: { name: "Atari ST/STE", icon: <GiConsoleController /> },
  64: { name: "Sega Master System", icon: <GiConsoleController /> },
  65: { name: "Atari 8-bit", icon: <GiConsoleController /> },
  66: { name: "Atari 5200", icon: <GiConsoleController /> },
  67: { name: "Intellivision", icon: <GiConsoleController /> },
  68: { name: "ColecoVision", icon: <GiConsoleController /> },
  69: { name: "BBC Microcomputer System", icon: <GiConsoleController /> },
  70: { name: "Vectrex", icon: <GiConsoleController /> },
  71: { name: "Commodore VIC-20", icon: <GiConsoleController /> },
  72: { name: "Ouya", icon: <GiConsoleController /> },
  73: { name: "BlackBerry OS", icon: <GiConsoleController /> },
  74: { name: "Windows Phone", icon: <GiConsoleController /> },
  75: { name: "Apple II", icon: <GiConsoleController /> },
  77: { name: "Sharp X1", icon: <GiConsoleController /> },
  78: { name: "Sega CD", icon: <GiConsoleController /> },
  79: { name: "Neo Geo MVS", icon: <GiConsoleController /> },
  80: { name: "Neo Geo AES", icon: <GiConsoleController /> },
  82: { name: "Web browser", icon: <GiConsoleController /> },
  84: { name: "SG-1000", icon: <GiConsoleController /> },
  85: { name: "Donner Model 30", icon: <GiConsoleController /> },
  86: { name: "TurboGrafx-16/PC Engine", icon: <GiConsoleController /> },
  87: { name: "Virtual Boy", icon: <GiConsoleController /> },
  88: { name: "Odyssey", icon: <GiConsoleController /> },
  89: { name: "Microvision", icon: <GiConsoleController /> },
  90: { name: "Commodore PET", icon: <GiConsoleController /> },
  91: { name: "Bally Astrocade", icon: <GiConsoleController /> },
  92: { name: "SteamOS", icon: <GiConsoleController /> },
  93: { name: "Commodore 16", icon: <GiConsoleController /> },
  94: { name: "Commodore Plus/4", icon: <GiConsoleController /> },
  95: { name: "PDP-1", icon: <GiConsoleController /> },
  96: { name: "PDP-10", icon: <GiConsoleController /> },
  97: { name: "PDP-8", icon: <GiConsoleController /> },
  98: { name: "DEC GT40", icon: <GiConsoleController /> },
  99: { name: "Family Computer (FAMICOM)", icon: <BsNintendoSwitch /> },
  100: { name: "Analogue electronics", icon: <GiConsoleController /> },
  101: { name: "Ferranti Nimrod Computer", icon: <GiConsoleController /> },
  102: { name: "EDSAC", icon: <GiConsoleController /> },
  103: { name: "PDP-7", icon: <GiConsoleController /> },
  104: { name: "HP 2100", icon: <GiConsoleController /> },
  105: { name: "HP 3000", icon: <GiConsoleController /> },
  106: { name: "SDS Sigma 7", icon: <GiConsoleController /> },
  107: { name: "Call-A-Computer time-shared mainframe computer system", icon: <GiConsoleController /> },
  108: { name: "PDP-11", icon: <GiConsoleController /> },
  109: { name: "CDC Cyber 70", icon: <GiConsoleController /> },
  110: { name: "PLATO", icon: <GiConsoleController /> },
  111: { name: "Imlac PDS-1", icon: <GiConsoleController /> },
  112: { name: "Microcomputer", icon: <GiConsoleController /> },
  113: { name: "OnLive Game System", icon: <GiConsoleController /> },
  114: { name: "Amiga CD32", icon: <GiConsoleController /> },
  115: { name: "Apple IIGS", icon: <GiConsoleController /> },
  116: { name: "Acorn Archimedes", icon: <GiConsoleController /> },
  117: { name: "Philips CD-i", icon: <GiConsoleController /> },
  118: { name: "FM Towns", icon: <GiConsoleController /> },
  119: { name: "Neo Geo Pocket", icon: <GiConsoleController /> },
  120: { name: "Neo Geo Pocket Color", icon: <GiConsoleController /> },
  121: { name: "Sharp X68000", icon: <GiConsoleController /> },
  122: { name: "Nuon", icon: <GiConsoleController /> },
  123: { name: "WonderSwan Color", icon: <GiConsoleController /> },
  124: { name: "SwanCrystal", icon: <GiConsoleController /> },
  125: { name: "PC-8801", icon: <GiConsoleController /> },
  126: { name: "TRS-80", icon: <GiConsoleController /> },
  127: { name: "Fairchild Channel F", icon: <GiConsoleController /> },
  128: { name: "PC Engine SuperGrafx", icon: <GiConsoleController /> },
  129: { name: "Texas Instruments TI-99", icon: <GiConsoleController /> },
  130: { name: "Nintendo Switch", icon: <BsNintendoSwitch /> },
  131: { name: "Nintendo PlayStation", icon: <GiConsoleController /> },
  132: { name: "Amazon Fire TV", icon: <GiConsoleController /> },
  133: { name: "Philips Videopac G7000", icon: <GiConsoleController /> },
  134: { name: "Acorn Electron", icon: <GiConsoleController /> },
  135: { name: "Hyper Neo Geo 64", icon: <GiConsoleController /> },
  136: { name: "Neo Geo CD", icon: <GiConsoleController /> },
  137: { name: "New Nintendo 3DS", icon: <SiNintendo3Ds /> },
  138: { name: "VC 4000", icon: <GiConsoleController /> },
  139: { name: "1292 Advanced Programmable Video System", icon: <GiConsoleController /> },
  140: { name: "AY-3-8500", icon: <GiConsoleController /> },
  141: { name: "AY-3-8610", icon: <GiConsoleController /> },
  142: { name: "PC-50X Family", icon: <GiConsoleController /> },
  149: { name: "PC-98", icon: <GiConsoleController /> },
  150: { name: "Turbografx-16/PC Engine CD", icon: <GiConsoleController /> },
  151: { name: "TRS-80 Color Computer", icon: <GiConsoleController /> },
  152: { name: "FM-7", icon: <GiConsoleController /> },
  153: { name: "Dragon 32/64", icon: <GiConsoleController /> },
  154: { name: "Amstrad PCW", icon: <GiConsoleController /> },
  155: { name: "Tatung Einstein", icon: <GiConsoleController /> },
  156: { name: "Thomson MO5", icon: <GiConsoleController /> },
  157: { name: "NEC PC-6000 Series", icon: <GiConsoleController /> },
  158: { name: "Commodore CDTV", icon: <GiConsoleController /> },
  159: { name: "Nintendo DSi", icon: <SiNintendo3Ds /> },
  160: { name: "Nintendo eShop", icon: <GiConsoleController /> },
  161: { name: "Windows Mixed Reality", icon: <GiConsoleController /> },
  162: { name: "Oculus VR", icon: <PiVirtualReality /> },
  163: { name: "SteamVR", icon: <PiVirtualReality /> },
  164: { name: "Daydream", icon: <GiConsoleController /> },
  165: { name: "PlayStation VR", icon: <FaPlaystation /> },
  166: { name: "Pokemon Mini", icon: <GiConsoleController /> },
  167: { name: "PlayStation 5", icon: <FaPlaystation /> },
  169: { name: "Xbox Series", icon: <FaXbox /> },
  170: { name: "Google Stadia", icon: <GiConsoleController /> },
};

export default platformMapping;
